#pragma once
// SAL stub - annotations are no-ops on Linux.
#define _In_
#define _Out_
#define _Inout_
#define _In_z_
#define _Out_z_
#define _In_reads_(x)
#define _Out_writes_(x)
#define _Inout_updates_(x)
#define _In_opt_
#define _Out_opt_
#define _Inout_opt_
#define _In_reads_bytes_(x)
#define _Out_writes_bytes_(x)
#define _In_reads_opt_(x)
#define _Out_writes_opt_(x)
#define _Check_return_
#define _Ret_maybenull_
#define _Ret_notnull_
#define _Success_(x)
#define _Must_inspect_result_
#define _Post_equals_last_error_
#define _Null_terminated_
#define _NullNull_terminated_
#define _Field_size_(x)
#define _Field_bytes_(x)
#define _Frees_ptr_
#define _Pre_notnull_
#define _Post_notnull_
#define _COM_Outptr_
#define _COM_Outptr_result_maybenull_
#define _Outptr_
#define _Outptr_result_nullonfailure_
#define _Outptr_opt_
#define _Outptr_opt_result_nullonfailure_
#define _Null_
#define _When_(x,y)
#define _At_(x,y)
#define _Analysis_assume_(x)
#define _Analysis_assume_succeeds_on_failure_
#define _Interlocked_
#define _Raises_SEH_exception_
#define _Range_(x,y)
#define _String_length_(x)